#!/usr/bin/env python3
import tensorflow.keras as keras
autoencoder = __import__('2-convolutional').autoencoder

encoder, decoder, auto = autoencoder((28, 28, 1), [16, 8, 8], (4, 4, 8))

for layer in decoder.layers:
    print(layer.__class__.__name__)
    try:
        if hasattr(layer, "activation"):
            print(layer.activation.__name__)
        print(layer.output_shape)
    except Exception:
        pass
